import type { Product, Order, Notification } from "./types"

export const allProducts: Product[] = [
  {
    id: 1,
    name: "قهوة اسبريسو برازيلي",
    category: "حبوب القهوة",
    price: 110,
    rating: 5,
    reviewCount: 120,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description:
      "انطلق في رحلة نكهة تأسر الحواس مع هذه القهوة المختارة بعناية مثالية لكل من يسعى لاستكشاف أعماق جديدة في عالم القهوة.",
    tastingNotes: ["شوكولاتة", "مكسرات", "كراميل"],
  },
  {
    id: 2,
    name: "قهوة فلتر كولومبي",
    category: "قهوة فلتر",
    price: 125,
    rating: 4.8,
    reviewCount: 95,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "قهوة كولومبية فاخرة تتميز بقوامها المتوازن وحمضيتها المشرقة.",
    tastingNotes: ["فواكه حمراء", "حمضيات", "قوام كريمي"],
  },
  {
    id: 3,
    name: "كبسولات إثيوبية",
    category: "الكبسولات",
    price: 90,
    rating: 4.9,
    reviewCount: 250,
    imageUrl: "/placeholder.svg?height=200&width=200",
    description: "كبسولات متوافقة مع أشهر الأجهزة، بنكهة إثيوبية فريدة.",
    tastingNotes: ["زهور", "توت أزرق", "ليمون"],
  },
  {
    id: 4,
    name: "قهوة اسبريسو غواتيمالا",
    category: "حبوب القهوة",
    price: 115,
    originalPrice: 130,
    rating: 4.7,
    reviewCount: 88,
    imageUrl: "/placeholder.svg?height=200&width=200",
    discount: "12%",
    description: "مزيج غني من غواتيمالا، مثالي للاسبريسو الغني بالكريمة.",
    tastingNotes: ["كاكاو", "توابل", "برتقال"],
  },
  {
    id: 5,
    name: "قهوة مبتكرة من كينيا",
    category: "الانتاج المبتكر",
    price: 150,
    originalPrice: 180,
    rating: 5,
    reviewCount: 75,
    imageUrl: "/placeholder.svg?height=200&width=200",
    discount: "17%",
    description: "تجربة فريدة من كينيا بطرق معالجة مبتكرة تبرز نكهات استثنائية.",
    tastingNotes: ["عنب أسود", "جريب فروت", "نبيذ"],
  },
]

export const mockOrders: Order[] = [
  {
    id: "ID-CAF202508051123",
    date: "2024-01-24 - 12:35",
    status: "تم التوصيل",
    itemCount: 10,
    address: "القصيم - عنيزة، المملكة العربية السعودية",
    items: [],
    total: 320,
  },
  {
    id: "ID-CAF202508051124",
    date: "2024-01-24 - 12:35",
    status: "قيد التجهيز",
    itemCount: 3,
    address: "الرياض - حي الملقا، المملكة العربية السعودية",
    items: [],
    total: 150,
  },
  {
    id: "ID-CAF202508051125",
    date: "2024-01-23 - 09:10",
    status: "ملغي",
    itemCount: 2,
    address: "جدة - حي السلامة، المملكة العربية السعودية",
    items: [],
    total: 95,
  },
  {
    id: "ID-CAF202508051126",
    date: "2024-01-24 - 14:00",
    status: "قيد التوصيل",
    itemCount: 5,
    address: "الدمام - حي الشاطئ، المملكة العربية السعودية",
    items: [],
    total: 210,
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 1,
    title: "تم شحن طلبك!",
    description: "طلبك #ID-CAF202508051124 في طريقه إليك.",
    date: "منذ 5 دقائق",
    read: false,
  },
  {
    id: 2,
    title: "خصم خاص لك",
    description: "استخدم كود COFFEE15 للحصول على خصم 15% على طلبك القادم.",
    date: "منذ 1 ساعة",
    read: false,
  },
  {
    id: 3,
    title: "تم توصيل الطلب",
    description: "تم توصيل طلبك #ID-CAF202508051123 بنجاح.",
    date: "بالأمس",
    read: true,
  },
]
